version: '3'

services:
  redis:
    image: "redis:alpine"
    networks:
    - sails_net
    ports:
    - "6379:6379"
    volumes:
    - ./redis.conf:/usr/local/etc/redis/redis.conf
  back:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      - REDIS_IP=redis
      - REDIS_PORT=6379
    networks:
    - sails_net
    env_file: ./env

networks:
  sails_net: